version: '3'
services:
  apache:
    image: httpd:latest
    ports:
      - "8080:80"

  tomcat:
    image: tomcat:latest
    ports:
      - "8081:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

