version: 1
config:
  - type: nameserver
    address:
      - 8.8.8.8
  - type: physical
    name: enp1s0
    subnets:
     - control: auto
       type: static
       address: {{IP_ADDRESS}}/24
       gateway: 192.168.122.1

